name: Update Chrome version

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Chrome version
        run: |
          LATEST_VERSION=$(curl -s "https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Linux&num=1" | jq -r '.[0].version')-1
          sed -i '' -e "s/^ARG CHROME_VERSION=.*$/ARG CHROME_VERSION=$LATEST_VERSION/" Dockerfile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
