name: Update Chrome version

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set latest version as env
        run: |
          LATEST_VERSION=$(curl -s "https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Linux&num=1" | jq -r '.[0].version')-1
          echo "LATEST_VERSION=$LATEST_VERSION" >> "$GITHUB_ENV"
      - name: Update Chrome version
        run: sed -i -e "s/^ARG CHROME_VERSION=.*$/ARG CHROME_VERSION=${{ env.LATEST_VERSION }}/" Dockerfile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update Chrome version to ${{ env.LATEST_VERSION }}
